import { DataItem } from '../interface/document-list.interface';

export const documentList: DataItem[] = [
  {
    id: '1',
    title: 'John Brown',
    document: "John Brown's document",
    createdDate: new Date('2023-01-01'),
  },
  {
    id: '2',
    title: 'Jim Green',
    document: "Jim Green's document",
    createdDate: new Date('2023-02-01'),
  },
  {
    id: '3',
    title: 'Joe Black',
    document: "Joe Black's document",
    createdDate: new Date('2023-01-15'),
  },
  {
    id: '4',
    title: 'Jim Red',
    document: "Jim Red's document",
    createdDate: new Date('2023-03-01'),
  },
  {
    id: '5',
    title: 'Alice Smith',
    document: "Alice Smith's document",
    createdDate: new Date('2023-02-15'),
  },
  {
    id: '6',
    title: 'Eve Davis',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-10'),
  },
  {
    id: '7',
    title: 'Charlie Johnson',
    document: "Alice Smith's document",
    createdDate: new Date('2023-01-20'),
  },
  {
    id: '8',
    title: 'Olivia White',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-05'),
  },
  {
    id: '9',
    title: 'Lucas Martin',
    document: "Alice Smith's document",
    createdDate: new Date('2023-02-28'),
  },
  {
    id: '10',
    title: 'Mia Thompson',
    document: "Alice Smith's document",
    createdDate: new Date('2023-01-25'),
  },
  {
    id: '11',
    title: 'Henry Garcia',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-15'),
  },
  {
    id: '12',
    title: 'Sophia Martinez',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-20'),
  },
  {
    id: '13',
    title: 'Liam Wilson',
    document: "Alice Smith's document",
    createdDate: new Date('2023-02-10'),
  },
  {
    id: '14',
    title: 'Ava Anderson',
    document: "Alice Smith's document",
    createdDate: new Date('2023-01-30'),
  },
  {
    id: '15',
    title: 'Noah Taylor',
    document: "Alice Smith's document",
    createdDate: new Date('2023-02-05'),
  },
  {
    id: '16',
    title: 'Isabella Lee',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-25'),
  },
  {
    id: '17',
    title: 'Oliver Harris',
    document: "Alice Smith's document",
    createdDate: new Date('2023-01-18'),
  },
  {
    id: '18',
    title: 'Emily Clark',
    document: "Alice Smith's document",
    createdDate: new Date('2023-02-22'),
  },
  {
    id: '19',
    title: 'James Lewis',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-12'),
  },
  {
    id: '20',
    title: 'Amelia Walker',
    document: "Alice Smith's document",
    createdDate: new Date('2023-01-28'),
  },
  {
    id: '21',
    title: 'Benjamin Hall',
    document: "Alice Smith's document",
    createdDate: new Date('2023-03-30'),
  },
];
